default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: impulso_development

test:
  <<: *default
  database: impulso_test

production:
  url: <%= ENV['DATABASE_URL'] %>
